config/routes.rb
BibliothekProject::Application.routes.draw do
  get "news/index"

  resources :consults

  resources :consultations

  resources :news

  get "inicio/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "inicio#index"
  ActiveAdmin.routes(self)

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    #Possible actions: create, :read, :update, :destroy
    user ||= AdminUser.new #invitado
 
    
    #can :read, BookAuthor
    can :read, ActiveAdmin::Page, :name => "Dashboard"
    
    can :read, Book
    can :read, Author
     
    # An admin can do the following:
    if user.role=='admin'
        can :manage, :all
    end
     
    # A reader can do the following:
    if user.role=='reader'

        #Manage his own account
        can :read, AdminUser, AdminUser.where(:id => user.id ) do |u|
            u.id == user.id
        end

        can :update, AdminUser, AdminUser.where(:id => user.id ) do |u|
            u.id == user.id
        end

        can :destroy, AdminUser, AdminUser.where(:id => user.id ) do |u|
            u.id == user.id
        end 


        #See his lendings       
        begin
            @reader = (Reader.all(:select => "id", :conditions => ["email = ?", user.email]))[0].id
            can :read, LendingBook, LendingBook.where(:reader_id => @reader ) do |lending_book|
              @reader==lending_book.reader_id
            end
        rescue Exception=>e
            can :read, LendingBook, LendingBook.where(:reader_id => 0 ) do |lending_book|
              0==lending_book.reader_id
            end
        end
        
        
        #See books and its authors
        
        

         
    end
    
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body

  validates :role, :password_confirmation, :presence => true


end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name, :nationality
  validates :name, :presence => true
  has_many :book_authors
  has_many :books, through: :book_authors
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :code, :title, :edition, :description, :quantity, :observation, :provider_id, :stock
  validates :title, :edition, :quantity, :presence => true
  validates :quantity, :edition, :numericality => { :only_integer => true }
  validates :quantity, :numericality => { :greater_than => 0 }
  validates :edition, :numericality => { :greater_than => 0 }
  has_many :book_authors
  has_many :authors, through: :book_authors

  has_many :lending_books
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
  attr_accessible :author_id, :book_id
  validates :author_id, :book_id, :presence => true
  belongs_to :author
  belongs_to :book
end

app/models/consult.rb
class Consult < ActiveRecord::Base
  attr_accessible :comment, :name
end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  attr_accessible :comment, :email, :name, :subject, :surname
  validates :comment, :email, :name, :subject, :surname, :presence => true
  validates :email, :format => { :with => /\A(([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,}))?\z/i,
    :message => "no tiene formato valido ejemplo@tecweb.cl" }
end

app/models/lending_book.rb
#encoding: utf-8
class MyValidator < ActiveModel::Validator
  def validate(lending_book)
  	#Cantidad de ese libro = 2
  	book = Book.where(:id => lending_book.book_id).first
    book_stock = book.quantity 
    #Cantidad de prestamos hechos para ese libro
    book_lendings_quantity = LendingBook.where(:book_id => book.id).length 
    if book_lendings_quantity == book_stock 
       lending_book.errors[:book_id] << "No está en stock."
    end
    
  end
end



class LendingBook < ActiveRecord::Base
  include ActiveModel::Validations
  validates_with MyValidator

  attr_accessible :book_id, :state, :days, :amount, :date, :reader_id, :observation, :return, :fine
  validates :reader_id,:book_id, :date, :state, :days, :presence => true
  validates :days, :numericality => { :only_integer => true }
  belongs_to :book
  belongs_to :reader

  scope :Prestados, where(:state => 0)
  scope :En_estante, where(:state => 1)
  scope :Recepcionados, where(:state => 2)
  scope :Todos

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :body, :title
  validates :body, :title, :presence => true
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone
  validates :address, :email, :name, :phone, :presence => true
  validates :email, :format => { :with => /\A(([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,}))?\z/i,
    :message => "no tiene formato valido ejemplo@tecweb.cl" }
  validates :phone, :format => { :with => /^-?((?:\d+|\d*)$)/,
    :message => "debe ingresar un numero valido" } 
     

end

app/models/reader.rb
class Reader < ActiveRecord::Base
  attr_accessible :address, :name, :observation, :email, :phone
  validates :name, :address, :presence => true
  has_many :lending_books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # Override build_footer method in ActiveAdmin::Views::Pages
  require 'active_admin_views_pages_base.rb'


  #rescue_from CanCan::AccessDenied do |exception|
  	#flash[:error] = "Acceso denegado."
  	#redirect_to root_url    
  #end

  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  def after_sign_out_path_for(resource_or_scope)
    "/"
  end

  #def authenticate_admin_user!
  #  redirect_to new_admin_user_session_path unless current_admin_user.role == 'admin'
  #end
end

app/controllers/consultations_controller.rb
class ConsultationsController < InheritedResources::Base

  def index
    @consultations = Consultation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consultations }
    end
  end

  def new
    @consultation = Consultation.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consultation }
    end
  end

def create
  @consultation = Consultation.new(params[:consultation])

  respond_to do |format|
  if @consultation.save
  ConsultationMailer.menssage(@consultation).deliver
  format.html { redirect_to(@consultation, :notice => 'La Consulta se ha enviado con exito.') }
  format.xml  { render :xml => @consultation, :status => :created, :location => @consultation }
  else
  format.html { render :action => "new" }
  format.xml  { render :xml => @consultation.errors, :status => :unprocessable_entity }
  end
  end
  end

  def show
    @consultation = Consultation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consultation }
    end
  end  



end

app/controllers/consults_controller.rb
class ConsultsController < InheritedResources::Base



def create
  @consultation = Consultation.new(params[:consultation])

  respond_to do |format|
  if @consultation.save
  ConsultationMailer.registration_confirmation(@consultation).deliver
  format.html { redirect_to(@consultation, :notice => 'User was successfully created.') }
  format.xml  { render :xml => @consultation, :status => :created, :location => @consultation }
  else
  format.html { render :action => "new" }
  format.xml  { render :xml => @consultation.errors, :status => :unprocessable_entity }
  end
  end
  end



end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	
  def index
    @noticias = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @noticias }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  	  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/consultations/_form.html.erb
<%= form_for(@consultation) do |f| %>
  <% if @consultation.errors.any? %>
<div id="error_explanation">
      <% if (@consultation.errors.count == 1) %>
      <h2>No se ha podido enviar la consulta, se ha encontrado <%= pluralize(@consultation.errors.count, "") %> error: </h2>
      <%else%>
      <h2>No se ha podido enviar la consulta, se han encontrado <%= pluralize(@consultation.errors.count, "") %> errores:</h2>
      <% end %>
      <ul>
      <% @consultation.errors.full_messages.each do |msg| %>
        <li><%= "> " + msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Asunto *" %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label "Nombre *" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Apellido *" %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label "E-mail *" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label "Comentario *" %><br />
    <%= f.text_area :comment, :cols=>"100", :rows=>"5" %>
  </div>
  <div class="actions">
    <div><%= f.submit "Enviar Consulta" %></div>
  </div>
<% end %>

app/views/consultations/edit.html.erb
<h1>Editing consultation</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultation %> |
<%= link_to 'Back', consultations_path %>

app/views/consultations/index.html.erb
<h1>Listing consultations</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @consultations.each do |consultation| %>
  <tr>
    <td><%= consultation.subject %></td>
    <td><%= consultation.name %></td>
    <td><%= consultation.surname %></td>
    <td><%= consultation.email %></td>
    <td><%= consultation.comment %></td>
    <td><%= link_to 'Show', consultation %></td>
    <td><%= link_to 'Edit', edit_consultation_path(consultation) %></td>
    <td><%= link_to 'Destroy', consultation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Consultation', new_consultation_path %>

app/views/consultations/new.html.erb
<div class="headContent">
    <h1>Consulta</h1>
</div>

<div class = "box">

<%= render 'form' %>

<a href="/inicio/index"> << Volver</a>	

</div>

app/views/consultations/show.html.erb
<div class="headContent">
    <h1>Detalle Consulta</h1>
</div>

<div class = "box">

<p id="notice"><%= notice %></p>

<p>
  <b>Asunto:</b>
  <%= @consultation.subject %>
</p>

<p>
  <b>Nombre:</b>
  <%= @consultation.name %>
</p>

<p>
  <b>Apellido:</b>
  <%= @consultation.surname %>
</p>

<p>
  <b>E-Mail:</b>
  <%= @consultation.email %>
</p>

<p>
  <b>Comentario:</b>
  <%= @consultation.comment %>
</p>


<a href="/inicio/index"> << Volver</a>   |


</div>

app/views/consults/_form.html.erb
<%= form_for(@consult) do |f| %>
  <% if @consult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consult.errors.count, "error") %> prohibited this consult from being saved:</h2>

      <ul>
      <% @consult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consults/edit.html.erb
<h1>Editing consult</h1>

<%= render 'form' %>

<%= link_to 'Show', @consult %> |
<%= link_to 'Back', consults_path %>

app/views/consults/index.html.erb
<h1>Listing consults</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @consults.each do |consult| %>
  <tr>
    <td><%= consult.name %></td>
    <td><%= consult.comment %></td>
    <td><%= link_to 'Show', consult %></td>
    <td><%= link_to 'Edit', edit_consult_path(consult) %></td>
    <td><%= link_to 'Destroy', consult, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Consult', new_consult_path %>

app/views/consults/new.html.erb
<h1>New consult</h1>

<%= render 'form' %>

<%= link_to 'Back', consults_path %>

app/views/consults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @consult.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @consult.comment %>
</p>


<%= link_to 'Edit', edit_consult_path(@consult) %> |
<%= link_to 'Back', consults_path %>

app/views/inicio/index.html.erb
<script type="text/javascript">
    $(document).ready(function(){
    var inicio = "<div>";
    var fin = "</div>"
    var valor = inicio; 
    var inicio_title = "<u><h2><b>";
    var fin_title = "</b></h2></u><br><br>"	;
    var contador = 0;
    $.get("/news.json", function(data) {
        for(i=data.length-1;i>=0 && contador<5;i--){
        	valor += inicio_title + data[i].title + fin_title + inicio + data[i].body + fin + "<hr>";
        	contador++;

        }
        document.getElementById("show_errors_receipt").innerHTML = valor;
    });
    });


</script>

<div class="headContent">
    <h1>Últimas Noticias</h1>
</div>

<div class = "box2">
      <h2 style="text-align: center;">Gracias por Visitar Bibliotech!</h2><br><hr>
      <div id = "show_errors_receipt">

</div>	

app/views/news/index.html.erb
<h1>News#index</h1>
<p>Find me in app/views/news/index.html.erb</p>